# Generated by Django 3.2b1 on 2021-03-15 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlidac', '0002_rizeni_predmet'),
    ]

    operations = [
        migrations.AddField(
            model_name='rizeni',
            name='datum_skonceni',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rizeni',
            name='datum_zahajeni',
            field=models.DateField(default=datetime.datetime(2019, 6, 24, 12, 44, 54)),
            preserve_default=False,
        ),
    ]
