# Generated by Django 3.2b1 on 2021-03-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlidac', '0003_auto_20210315_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='rizeni',
            name='probehlo_odvolani',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
